/**
 * The "もったいない" voice lines, generated by ElevenLabs Eleven v3.
 *
 * GET /api/mottainai?level=empty|light|half|most|untouched&v=0..2
 *
 * The lines are a fixed set (lib/voiceLines.ts), each synthesized once per
 * server process and served from memory after that. The route accepts a
 * level and variant index, never free text, so the public endpoint can't be
 * used to spend the API key on arbitrary speech.
 */

import { VOICE_LINES, isVoiceLevel } from "@/lib/voiceLines";

const ENDPOINT = "https://api.elevenlabs.io/v1/text-to-speech";
// Chosen demo voice; override with ELEVENLABS_VOICE_ID to try another.
const VOICE_ID = process.env.ELEVENLABS_VOICE_ID || "a0MsDWokG5Xsuji8g8er";
// v3 performs the bracketed audio tags ([sighs], [shouts], …).
const MODEL_ID = process.env.ELEVENLABS_MODEL_ID || "eleven_v3";
// ElevenLabs caps concurrent requests per plan; the browser warms every
// clip at once, so queue synthesis instead of tripping 429s.
const MAX_CONCURRENT = 2;

const cache = new Map<string, Promise<ArrayBuffer>>();
let active = 0;
const waiting: Array<() => void> = [];

async function withSlot<T>(task: () => Promise<T>): Promise<T> {
  if (active >= MAX_CONCURRENT) {
    await new Promise<void>((resolve) => waiting.push(resolve));
  }
  active++;
  try {
    return await task();
  } finally {
    active--;
    waiting.shift()?.();
  }
}

async function synthesize(
  text: string,
  stability: number,
  speed: number,
): Promise<ArrayBuffer> {
  const apiKey = process.env.ELEVENLABS_API_KEY;
  if (!apiKey) throw new Error("ELEVENLABS_API_KEY is not set on the server");

  const res = await fetch(
    `${ENDPOINT}/${VOICE_ID}?output_format=mp3_44100_128`,
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "xi-api-key": apiKey,
      },
      body: JSON.stringify({
        text,
        model_id: MODEL_ID,
        voice_settings: { stability, similarity_boost: 0.75, speed },
      }),
      signal: AbortSignal.timeout(30_000),
    },
  );
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`ElevenLabs error ${res.status}: ${body.slice(0, 300)}`);
  }
  return res.arrayBuffer();
}

export async function GET(request: Request) {
  const params = new URL(request.url).searchParams;
  const level = params.get("level") ?? "half";
  if (!isVoiceLevel(level)) {
    return Response.json(
      { error: `Unknown level "${level}"` },
      { status: 400 },
    );
  }
  const config = VOICE_LINES[level];
  const variant = Number(params.get("v") ?? 0);
  if (!Number.isInteger(variant) || !config.variants[variant]) {
    return Response.json(
      { error: `Unknown variant "${params.get("v")}"` },
      { status: 400 },
    );
  }

  const key = `${level}:${variant}`;
  let pending = cache.get(key);
  if (!pending) {
    pending = withSlot(() =>
      synthesize(config.variants[variant], config.stability, config.speed),
    );
    cache.set(key, pending);
  }
  try {
    const audio = await pending;
    return new Response(audio, {
      headers: {
        "content-type": "audio/mpeg",
        // The server already caches the clip; don't let browsers pin an
        // old voice or line after either changes.
        "cache-control": "no-store",
      },
    });
  } catch (err) {
    cache.delete(key); // let the next request retry
    return Response.json({ error: (err as Error).message }, { status: 503 });
  }
}
